name: kendo_keiko_timer
description: Kendo Keiko training interval timer.

# Prevent accidentally publishing to pub.dev using `pub publish`
publish_to: 'none'

version: 1.4.3+10

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^1.0.1
  flutter_colorpicker: ^1.0.3
  numberpicker: ^2.1.1
  shared_preferences: ^2.0.6
  wakelock: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/boop.mp3
  - assets/dingdingding.mp3
  - assets/pip.mp3
  - assets/hajime.mp3
  - assets/yame.mp3

